const config = {
  clearLocalStorageInNewVersion: true,
  language: 'zh',
  defaultServerLanguage: 'zs',
  recommendedEventRoundTime: 10000,
  balancePollingTime: 15000,
  newsPollingTime: 15000,
  alertMessageKeepTime: 5000,
  defaultOddsFormat: 'decimal',
  betTypes: [
    { label: 'single', value: 'single' },
    { label: 'multiple', value: 'multiple' },
    { label: 'system', value: 'system' },
  ],
  betslipPriceChangeCodeMap: {
    ask: 2,
    upper: 1,
    free: 2,
  },
  alertsContent: {
    betCountLimitError: 'The Betslip items have reached the upper limit',
    loginStateError: 'Please login first',
    betslipStakeError: 'Please check betslip and stakes',
  },
  defaultBetType: 'single',
  sportIds: [74, 75, 76, 77, 78, 80, 82, 83, 157, 158, 164, 169, 176, 185],
  sportIdMap: {
    '74': { alias: 'callofduty', name: '使命召唤' },
    '75': { alias: 'csgo', name: '反恐精英' },
    '76': { alias: 'dota2', name: '刀塔2' },
    '77': { alias: 'lol', name: '英雄联盟' },
    '78': { alias: 'hearthstone', name: '炉石传说' },
    '80': { alias: 'overwatch', name: '守望先锋' },
    '82': { alias: 'starcraft', name: '星际争霸' },
    '83': { alias: 'starcraft2', name: '星际2' },
    '157': { alias: 'rocketleague', name: '火箭联盟' },
    '158': { alias: 'kingofglory', name: '王者荣耀' },
    '164': { alias: 'pubg', name: '绝地求生' },
    '169': { alias: 'warcraft3', name: '魔兽3' },
    '176': { alias: 'fortnite', name: '堡垒之夜' },
    '185': { alias: 'rainbow6', name: '彩虹六号' },
  },
  nonVersusMarketType: [
    'DoubleChance',
    'CorrectScore',
    'MatchResult',
    'GameLargestMultiKill',
    'P1XP2',
    'Game1LargestMultiKill',
    'Game2LargestMultiKill',
    'Game3LargestMultiKill',
    'Game4LargestMultiKill',
    'Game5LargestMultiKill',
    'Game1FirstDragonType',
    'Game2FirstDragonType',
    'Game3FirstDragonType',
    'Game4FirstDragonType',
    'Game5FirstDragonType',
    'GameFirstActiveRuneType',
  ],
  summaryListData: {
    paths: ['', 'champion', 'result'],
    tabs: {
      upcoming: { name: 'Upcoming', path: '' },
      champion: { name: 'Champion', path: 'champion' },
      result: { name: 'Result', path: 'result' },
    },
  },
  balanceHistoryModal: {
    tabs: {
      balanceHistory: { name: 'balanceHistory' },
    },
  },
  betHistroyModal: {
    tabs: {
      all: { name: 'all' },
      single: { name: 'single' },
      multiple: { name: 'multiple' },
      system: { name: 'system' },
    },
  },
  betTypeCodeConvert: {
    single: 1,
    multiple: 2,
    system: 3,
  },
  defaultDateRange: 7,
  betHistoryDefaultDateRange: 7,
  balanceHistoryDefaultDateRange: 30,
  priceDecimalPlaceDisplay: 2,
  balanceDecimalPlaceDisplay: 3,
  APIBetTypeMap: {
    Single: 'single',
    Multiple: 'multiple',
    System: 'system',
  },
  defaultPriceChangeHandleType: 'ask',
  betslipPriceChangeRadioGroup: {
    ask: { value: 'ask', label: 'Always ask' },
    upper: { value: 'upper', label: 'Accept higher odds' },
    free: { value: 'free', label: 'Accept any odds' },
  },
  betslipBetCountMAX: 16,
  betslipSystemCountMIN: 3,
  eventResultOfGameCancel: 3,
  eventResultOfMarketCancel: 4,
  eventResultOfWin: 1,
  eventResultOfNoResult: 0,
  championGamelistTitleTransitionTime: 5000,
  serverReconnectingIntervalTime: 10000,
  serverCode: {
    OK: 0,
    LoginFailed: 1002,
    ProductionNotOpen: 1004,
    ProductionMaintain: 1005,
    InsufficientBalance: 2002,
    SelectionNotExists: 2004,
  },
  langMap: {
    en: 'en',
    id: 'en',
    ko: 'en',
    ms: 'en',
    th: 'en',
    vi: 'en',
    zs: 'zh',
    ja: 'ja',
  },
  teamIconCdnUrl: 'https://cdn.rixinmould.com/images/b/',

  newsStayTime: 5000,
  upcomingGameDefaultDays: 30,
  championGameDefaultDays: 30,
  resultGameDefaultDays: 3,
  gameListTabs: {
    upcoming: { label: 'Upcoming', value: '' },
    champion: { label: 'Champion', value: 'champion' },
    result: { label: 'Result', value: 'result' },
  },
  MatchStatus: {
    NotStarted: 0,
    Started: 1,
    Completed: 2,
    Canceled: 3,
  },
  betslipBetTypeItems: {
    single: { label: 'single', value: 'single' },
    multiple: { label: 'multiple', value: 'multiple' },
    system: { label: 'system', value: 'system' },
  },
  oddsFormat: {
    decimal: { label: 'decimal', value: 'decimal' },
  },
  recordNavItem: {
    betHistory: { label: 'Bet history', value: 'betHistory' },
    balanceHistory: { label: 'Balance history', value: 'balanceHistory' },
  },
  dayRangeFilterItems: [
    { label: '3 days', value: 3 },
    { label: '5 days', value: 5 },
    { label: '7 days', value: 7 },
    { label: '14 days', value: 14 },
    { label: '30 days', value: 30 },
    { label: '60 days', value: 60 },
  ],
  betHistoryBetTypeItems: [
    { label: 'All', value: 'all' },
    { label: 'Single', value: 'single' },
    { label: 'Multiple', value: 'multiple' },
    { label: 'System', value: 'system' },
  ],
  betHistoryDefaultBetType: 'all',
  betHistoryDefaultDays: 7,
  betHistoryMAXDays: 30,
  balanceHistoryDefaultDays: 30,
  balanceHistoryMAXDays: 30,
  betHistoryNoResultStateName: 'Unsettled',
};

module.exports = config;
